PROGRAM_NAME = "basicDataTypes"

compile:
	@gcc -fdiagnostics-color=always -g source/${PROGRAM_NAME}.c -o dist/${PROGRAM_NAME}.exe
	@echo 'compiling ${PROGRAM_NAME} ...'

run:
	@echo 'running ...'
	@./dist/${PROGRAM_NAME}.exe

build: compile run
	